# Generated by Django 2.2.2 on 2020-01-29 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='用户名', max_length=20)),
                ('password', models.CharField(db_column='password', max_length=20)),
                ('email', models.EmailField(max_length=50)),
            ],
            options={
                'db_table': 'manager',
            },
        ),
    ]
