# Generated by Django 2.2.2 on 2020-02-01 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_token_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
