# Generated by Django 2.2.2 on 2020-02-04 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20200204_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='id',
            field=models.BigAutoField(db_column='序号', primary_key=True, serialize=False),
        ),
    ]
