# Generated by Django 2.2.2 on 2020-02-02 02:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Talking',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, db_column='用户名', max_length=20, null=True)),
                ('email', models.EmailField(db_column='email', max_length=50)),
                ('talk', models.CharField(db_column='内容', max_length=600)),
                ('article', models.ForeignKey(db_column='对应文章', on_delete=django.db.models.deletion.CASCADE, to='article.Article')),
            ],
            options={
                'db_table': 'Talking',
            },
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, db_column='用户名', max_length=20, null=True)),
                ('email', models.EmailField(db_column='email', max_length=50)),
                ('talk', models.CharField(db_column='内容', max_length=600)),
                ('article', models.ForeignKey(db_column='对应文章', on_delete=django.db.models.deletion.CASCADE, to='article.Article')),
                ('talking', models.ForeignKey(db_column='对于评论', on_delete=django.db.models.deletion.CASCADE, to='talking.Talking')),
            ],
            options={
                'db_table': 'Reply',
            },
        ),
    ]
