# Generated by Django 2.2.2 on 2020-02-02 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('talking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='article',
        ),
    ]
