# Generated by Django 2.2.2 on 2020-02-02 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talking', '0002_remove_reply_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='username',
            field=models.CharField(blank=True, db_column='用户名', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='talking',
            name='username',
            field=models.CharField(blank=True, db_column='用户名', max_length=50, null=True),
        ),
    ]
