# Generated by Django 2.2.2 on 2020-02-02 07:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('talking', '0003_auto_20200202_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='talking',
            name='talking_time',
            field=models.DateTimeField(auto_now_add=True, db_column='评论时间', default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
